// Generated by CoffeeScript 1.9.2
var SeussQueueBusy, SeussQueueCorrupt, util;

util = require('util');

SeussQueueBusy = function() {
  return this.message = 'WARNING: Lock file found, is the queue in use?\nDelete if recovering from a crash.';
};

util.inherits(SeussQueueBusy, Error);

SeussQueueCorrupt = function() {
  return this.message = 'WARNING: The queue file appears corrupt.\nFix or remove to continue.';
};

util.inherits(SeussQueueBusy, Error);

module.exports = {
  SeussQueueBusy: SeussQueueBusy,
  SeussQueueCorrupt: SeussQueueCorrupt
};
