// Generated by CoffeeScript 1.9.2
var Queue;

Queue = function(queue) {
  var compact, offset;
  if (queue == null) {
    queue = [];
  }
  offset = 0;
  compact = function() {
    queue = queue.slice(offset);
    return offset = 0;
  };
  return {
    enqueue: function(item) {
      return queue.push(item);
    },
    dequeue: function() {
      var item;
      if (queue.length === 0) {
        return void 0;
      }
      item = queue[offset];
      offset++;
      if (offset * 2 >= queue.length) {
        compact();
      }
      return item;
    },
    peek: function() {
      if (queue.length === 0) {
        return void 0;
      }
      return queue[offset];
    },
    length: function() {
      return queue.length - offset;
    },
    all: function() {
      compact();
      return queue;
    },
    compact: compact
  };
};

module.exports = Queue;
