// Generated by CoffeeScript 1.9.2
var fs, markers, roundbyte;

fs = require('graceful-fs');

markers = require('./markers');

roundbyte = require('./roundbyte');

module.exports = function(path) {
  var buffer, length, marker, message, offset;
  buffer = fs.readFileSync(path);
  offset = 0;
  while (offset < buffer.length) {
    marker = buffer.readUInt32BE(offset);
    offset += 4;
    if (marker === markers.noop) {
      break;
    }
    if (marker === markers.enqueue) {
      length = buffer.readUInt32BE(offset);
      offset += 4;
      message = buffer.toString('utf8', offset, offset + length);
      offset += length;
      offset = roundbyte(offset);
      console.log("enqueue " + message);
    } else if (marker === markers.dequeue) {
      console.log('dequeue');
    } else {
      throw 'Corrupt queue file - fix or remove';
    }
  }
  return console.log('noop');
};
